### PR TITLE
Modify wacom_serial5 Thumbwheel -> Rel Scrollwheel

### PR DESCRIPTION
**Pull request by MackPI**
Added new code to take thumbwheel absolute value and translate that into scroll wheel actions with variable speeds.

### CODE REVIEW

**Comment by RoaldFre** [comment]
Hi MackPI,

Nice to see that people are using and contributing to the serial wacom driver! :-)

I don't have a 4D mouse to test the code myself, but ideally switching between absolute and relative ('scrollwheel') mode should be something that can be done at runtime through some file in /sys or /proc. Likewise, the scroll sensitivity/delay of 800 should probably be configurable like that as well.

I'm not too sure of the precision of those wheels, but if it springs back to the center and ends up at some small non-zero value (e.g stuck at +1 or -2 or something like that), then that can accumulate over time to give spurious/unexpected scroll inputs. If that's the case, you may need to introduce a deadzone where you don't take into account wheel deviations between -x and +x, for instance. You probably also want to reset the accumulated value when the wheel hits zero again (or enters this small deadzone), as well, so that the first subsequent scroll action behaves as expected.

I probably won't have time to look into this myself the coming days (and I can't test it with a 4D mouse), but if you can find the time to do those adjustments, I'll gladly merge the changes ;-)

Cheers!
Roald

**Comment by MackPI** [comment]
Hi Roald,

First off, Thank you for the driver to begin with.  I have been using it for a few months and I am very happy with it.

I am an electronics engineer and I specialize in embedded systems.  The only experience I have working with kernel level drivers is this very simple change to your software.  My experience suggests that there is a deadband built into the mouse. 

I think getting the thumb wheel absolute value at any given time through the /sys folder would be a good way to learn how to use this kernel feature.

I have started my research by searching on Google for sysfs and I am starting to understand a little.

Thank you,
Steve

**Comment by MackPI** [comment]
I think I have implemented the changes you requested.  I am not a software developer, Please review my code carefully.  It is working well for me, but I don't know if I have done something stupid.

Thank you,
Steve

**Comment by RoaldFre** [comment]
Hi Steve!

Looking good!

I've got two remaining remarks regarding the behaviour of the code:

1) line 505: I assume you want to subtract the offset instead of add it? Based on the way I read your description of the parameter: the offset is meant as the value that the wheel ends up in when you let go of it, so you want to remap that to zero by subtracting it from the newly read value? Maybe to make this more easy, I would suggest that you always report the absolute value in the (read-only) thumbwheel parameter so users can just read that out and set that value for the offset directly from that -- now it gives you the relative throttle if you are using the scrolling option.

2) Something I think of: if you have a small delay value set (eg 10), and you push the wheel to its maximum extension (eg 1000), you probably want to send a rel event of 100 instead of rel events of 1. (I guess that if you keep the wheel at 1000 all the time, you won't be able to 'catch up' with subtracting 10 every time anyway?)
I.e. instead of checking delay > pos_delay and then subtracting pos_delay once, make it so that in that case throttle = -delay / pos_delay (integer division where the minus sign is because your code has that too, I guess scrolling 'up' is the reverse of what is 'up' for the thumb wheel's absolute value?), then just update delay as delay = delay + throttle * pos_delay (+ sign because the above has a - sign), and analogously for min_delay (+ and - signs probably switched, now, because min_delay is negative)
You could check if that behaves more naturally for small delay values.

And lastly some minor style remarks:

- line 509: I would use a logical and (&&) instead of a bitwise one (&) for clarity and remove the space before the unary '-' sign before the last 'deadband'.
- line 512: add a space before the 0 for consistency
- lines 69-79: add spaces after the commas before 'int' for consistency
- line 504: you forgot the month in the SEM tag (but I would suggest removing that altogether: we have git to see who authored what ;-))
- line 529: likewise, this is what git is for, so that line may be removed
- Finally, according to the Linux kernel coding style guide ( https://www.kernel.org/doc/Documentation/CodingStyle ), the first part of the if statement on line 507 should be enclosed in braces (because the else part is in braces over multiple lines); on lines 515, 519, 523: there should be a space before the opening curly brace at the end of those lines; and lines 518-519 and 522-523 should be on a single line.

By the way, thank you for putting time and effort into making this driver better for everyone! (Got to love open source software, right? :-))

Cheers!
Roald

**Comment by MackPI** [comment]
Hi Roald,
I think I have made all your requested changes.
I didn't change the place thumbwheel is captured.  thumbwheel is getting updated with the value of throttle immediately after it has been decoded. If I missed something there, I would like to know about it.
Is there a document I should update describing the parameters that I made available?

Thank you,
Steve

**Comment by RoaldFre** [comment]
Hi Steve,

Regarding documenting the parameters, you are welcome to add them in the README file! :-)

I've went over the entire code now (instead of the individual patches), and everything looks neat, except for one thing that I was wondering about: the ABS_WHEEL events.
Line 758 registers an absolute wheel for the mouse (from -1023 to 1023) [this was from the first patch], but the ABS_WHEEL is used for the airbrush and ranges from 0 to 1023 (it is declared right below, so that will conflict). We use ABS_THROTTLE for the absolute thumb wheel because that ABS_WHEEL is already taken, I guess -- I don't have mouse nor airbrush to test.
So I would think that line 758 has to go.
Similarly, I would think that line 395 should be uncommented again and 396 removed.

But, this got me thinking about the 4 dimensions of the 4D mouse. There is 2D from the x/y coordinates, and 1D from the thumbwheel (ABS_THROTTLE), and the other one -- as far as I understand it -- should be the rotation of the mouse on the tablet itself (which we send to ABS_RZ).
However, we never seem to declare that ABS_RZ axis nor its range (based on the code, I'm assuming/guessing that it ranges from -899 to +899 -- barring off-by-one errors). We should probably properly declare that axis (eg instead of the ABS_WHEEL on line 758, we should make it the ABS_RZ with the correct range), I'm not sure if it even works at all right now.

Could you test if that works correctly with your mouse when it is properly declared? And verify the correct range? (IIRC, you can test this/get the raw events with evtest)

That's the last thing I'll ask, I swear! ;-)

Cheers!
Roald

**Comment by MackPI** [comment]
Hi Roald,
I didn't know what event to look at with evtest.  So, I exported the rotation value to /sys and did a cat of that value from conky.  Mouse straight forward is 0 with negative values turning left and positive turning right. Mouse pointed straight back is +-899.  I verified that I saw both positive 1 and negative 1 to verify no off by one errors.  I also watched carefully to verify +-900 did not show up.
I have removed the test code and will update it tonight.

Thanks,
Steve

**Comment by MackPI** [comment]
Hi Roald,
I think it's done,
Scrutiny is gladly accepted.
Thanks again,
Steve

**Comment by RoaldFre** [comment]
Looks good! Thanks for improving the driver! :-)

Cheers,
Roald

**Pull request merged**
